"""Turn input collection, media preprocessing, and cancellation."""

from __future__ import annotations

import asyncio
import base64
import hashlib
import json
import logging
import time
from typing import Any, Literal

from sglang_omni.preprocessing.image import prepare_image_bytes_for_wire
from sglang_omni.serve.realtime.audio_buffer import RealtimeAudioBuffer
from sglang_omni.serve.realtime.protocol.common import *  # noqa: F403
from sglang_omni.serve.realtime.protocol.models import ImageFrame, TurnBuffer
from sglang_omni.utils.structured_logs import (
    emit_structured_log as _base_emit_structured_log,
    new_trace_id,
)

logger = logging.getLogger(__name__)


def emit_structured_log(log_type: str, event: str, **fields: Any) -> bool:
    from sglang_omni.serve.realtime import multimodal

    hook = getattr(multimodal, "emit_structured_log", _base_emit_structured_log)
    return hook(log_type, event, **fields)


class TurnInputComponent:
    """Input-side Turn lifecycle behavior."""

    async def handle_turn_start(self, event: dict[str, Any]) -> None:
        self._require_started()
        turn_id = event.get("turn_id")
        if not isinstance(turn_id, str) or not turn_id.strip():
            raise ValueError(
                "turn_id must be generated by the caller and be a non-empty string"
            )
        turn_id = turn_id.strip()
        emit_structured_log(
            "lifecycle",
            "turn_start_received",
            session_id=self.session_id,
            turn_id=turn_id,
        )
        turn_origin, text_role, trigger = self._parse_turn_semantics(event)
        if turn_id in self.used_turn_ids:
            raise ValueError(f"turn_id has already been used: {turn_id}")
        preempted_turn_id: str | None = None
        if self.active_turn is not None:
            if turn_origin != TURN_ORIGIN_USER:
                raise ValueError("another turn is already active")
            preempted_turn = self.active_turn
            preempted_turn_id = preempted_turn.turn_id
            emit_structured_log(
                "lifecycle",
                "turn_preemption_requested",
                level="warning",
                session_id=self.session_id,
                turn_id=preempted_turn_id,
                trace_id=preempted_turn.trace_id,
                replacement_turn_id=turn_id,
                preempted_turn_origin=preempted_turn.turn_origin,
                preempted_turn_phase=preempted_turn.phase,
                reason="new_user_turn",
            )
            # User input has the highest admission priority. Complete old-Turn
            # cancellation before publishing turn.started for the replacement,
            # so clients cannot append media while old inference is still live.
            await self._cancel_active_turn(
                send_event=True,
                expected_turn=preempted_turn,
            )
            emit_structured_log(
                "lifecycle",
                "turn_preemption_completed",
                session_id=self.session_id,
                turn_id=preempted_turn_id,
                trace_id=preempted_turn.trace_id,
                replacement_turn_id=turn_id,
                reason="new_user_turn",
            )
        self.used_turn_ids.add(turn_id)
        if turn_origin == TURN_ORIGIN_USER:
            self._session_turn_sequence += 1
        self.active_turn = TurnBuffer(
            turn_id=turn_id,
            started_at=time.perf_counter(),
            audio=RealtimeAudioBuffer(source_sr=16000, target_sr=16000),
            images=[],
            audio_seqs=set(),
            image_seqs=set(),
            turn_origin=turn_origin,
            text_role=text_role,
            trigger=trigger,
            trace_id=new_trace_id(self.session_id, turn_id),
            session_turn_seq=(
                self._session_turn_sequence
                if turn_origin == TURN_ORIGIN_USER
                else 0
            ),
        )
        emit_structured_log(
            "lifecycle",
            "turn_started",
            session_id=self.session_id,
            turn_id=turn_id,
            trace_id=self.active_turn.trace_id,
            turn_origin=turn_origin,
            text_role=text_role,
            trigger=trigger,
            modalities=list(self.modalities),
            preempted_turn_id=preempted_turn_id,
        )
        sent = await self.send(
            {
                "type": "turn.started",
                "session_id": self.session_id,
                "turn_id": turn_id,
            }
        )
        if sent:
            emit_structured_log(
                "lifecycle",
                "turn_started_sent",
                session_id=self.session_id,
                turn_id=turn_id,
                trace_id=self.active_turn.trace_id,
            )
    async def handle_audio_append(self, event: dict[str, Any]) -> None:
        turn = self._require_collecting_turn(event)
        seq = self._positive_int(event.get("seq"), "seq")
        audio = event.get("audio")
        if not isinstance(audio, str) or not audio:
            raise ValueError("audio must be a non-empty base64 string")
        try:
            decoded = base64.b64decode(audio, validate=True)
        except Exception as exc:
            raise ValueError("audio is not valid base64") from exc
        if len(decoded) % 2:
            raise ValueError("PCM16 audio must contain an even number of bytes")
        chunk_hash = hashlib.sha256(decoded).hexdigest()
        if seq in turn.audio_seqs:
            if turn.audio_chunk_hashes.get(seq) != chunk_hash:
                raise ValueError(
                    f"audio seq {seq} conflicts with the previously accepted chunk"
                )
            turn.duplicate_audio_chunks += 1
            await self._ack_media(turn, "audio", seq, duplicate=True)
            return
        expected_seq = turn.audio_chunk_count + 1
        if seq != expected_seq:
            raise ValueError(
                f"audio seq must be monotonic starting at 1; expected {expected_seq}, got {seq}"
            )
        if turn.audio_chunk_count >= MAX_AUDIO_CHUNKS_PER_TURN:
            raise ValueError(f"audio chunk count exceeds {MAX_AUDIO_CHUNKS_PER_TURN}")
        turn.audio.append_b64(audio)
        turn.audio_seqs.add(seq)
        turn.audio_chunk_hashes[seq] = chunk_hash
        turn.audio_chunk_count += 1
        if turn.first_audio_received_at is None:
            turn.first_audio_received_at = time.perf_counter()
            emit_structured_log(
                "lifecycle",
                "turn_first_audio_received",
                session_id=self.session_id,
                turn_id=turn.turn_id,
                trace_id=turn.trace_id,
                seq=seq,
                audio_bytes=len(decoded),
                sample_rate_hz=16000,
            )
        await self._ack_media(turn, "audio", seq)
    async def _prepare_image_frame(
        self,
        turn: TurnBuffer,
        *,
        seq: int,
        decoded: bytes,
    ) -> dict[str, Any]:
        started = time.perf_counter()
        try:
            async with self._image_preprocess_semaphore:
                if turn.phase not in {
                    TURN_PHASE_COLLECTING,
                    TURN_PHASE_PROCESSING,
                }:
                    return {
                        "status": "stale",
                        "elapsed_ms": (time.perf_counter() - started) * 1000.0,
                        "prepared_bytes": 0,
                    }
                payload = await asyncio.to_thread(
                    prepare_image_bytes_for_wire,
                    decoded,
                )
            prepared_bytes = len(payload["pixel_bytes"])
            if prepared_bytes > MAX_PREPARED_IMAGE_BYTES_PER_FRAME:
                status = "frame_too_large"
                payload = None
                prepared_bytes = 0
            elif (
                turn.prepared_image_bytes + prepared_bytes
                > MAX_PREPARED_IMAGE_BYTES_PER_TURN
            ):
                status = "turn_budget_exceeded"
                payload = None
                prepared_bytes = 0
            else:
                status = "prepared"
                turn.prepared_image_bytes += prepared_bytes
            return {
                "status": status,
                "payload": payload,
                "elapsed_ms": (time.perf_counter() - started) * 1000.0,
                "prepared_bytes": prepared_bytes,
            }
        except Exception as exc:
            logger.warning(
                "[SESSION_ACTION_REALTIME] image preprocessing fell back "
                "session_id=%s turn_id=%s seq=%s error=%s",
                self.session_id,
                turn.turn_id,
                seq,
                exc,
            )
            return {
                "status": "failed",
                "error": str(exc),
                "elapsed_ms": (time.perf_counter() - started) * 1000.0,
                "prepared_bytes": 0,
            }
    @staticmethod
    def _discard_image_preprocess(turn: TurnBuffer, frame: ImageFrame) -> None:
        task = frame.preprocess_task
        if task is None:
            return
        if task.done() and not task.cancelled():
            try:
                result = task.result()
            except Exception:
                result = {}
            turn.prepared_image_bytes = max(
                turn.prepared_image_bytes - int(result.get("prepared_bytes", 0)),
                0,
            )
        elif not task.done():
            task.cancel()
        frame.preprocess_task = None
    async def _resolve_prepared_images(
        self,
        turn: TurnBuffer,
        frames: list[ImageFrame],
    ) -> tuple[list[Any], dict[str, Any]]:
        wait_started = time.perf_counter()
        emit_structured_log(
            "performance",
            "image_preprocess_begin",
            session_id=self.session_id,
            turn_id=turn.turn_id,
            trace_id=turn.trace_id,
            frame_count=len(frames),
        )
        tasks = [frame.preprocess_task for frame in frames if frame.preprocess_task]
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
        wait_ms = (time.perf_counter() - wait_started) * 1000.0
        images: list[Any] = []
        results: list[dict[str, Any]] = []
        for frame in frames:
            task = frame.preprocess_task
            result: dict[str, Any] = {}
            if task is not None and task.done() and not task.cancelled():
                try:
                    value = task.result()
                except Exception:
                    value = None
                if isinstance(value, dict):
                    result = value
            payload = result.get("payload")
            images.append(payload if isinstance(payload, dict) else frame.data_uri)
            results.append(result)
        statuses = [str(result.get("status", "not_scheduled")) for result in results]
        stats = {
            "scheduled_count": len(tasks),
            "prepared_count": statuses.count("prepared"),
            "fallback_count": sum(
                status not in {"prepared", "not_scheduled"} for status in statuses
            ),
            "not_scheduled_count": statuses.count("not_scheduled"),
            "worker_total_ms": round(
                sum(float(result.get("elapsed_ms", 0.0)) for result in results), 3
            ),
            "commit_wait_ms": round(wait_ms, 3),
            "prepared_bytes": sum(
                int(result.get("prepared_bytes", 0)) for result in results
            ),
            "statuses": statuses,
        }
        turn.image_preprocess_stats = stats
        emit_structured_log(
            "performance",
            "image_preprocess_end",
            session_id=self.session_id,
            turn_id=turn.turn_id,
            trace_id=turn.trace_id,
            **stats,
        )
        return images, stats
    async def handle_image_append(self, event: dict[str, Any]) -> None:
        turn = self._require_collecting_turn(event)
        seq = self._positive_int(event.get("seq"), "seq")
        image_role = event.get(
            "image_role", DEFAULT_IMAGE_ROLE_BY_ORIGIN[turn.turn_origin]
        )
        if not isinstance(image_role, str) or image_role not in IMAGE_ROLES:
            raise ValueError("image_role must be 'user_camera' or 'avatar_state'")
        image = event.get("image")
        if not isinstance(image, str) or not image:
            raise ValueError("image must be a non-empty base64 string or data URI")
        mime_type = event.get("mime_type", "image/jpeg")
        if mime_type not in ("image/jpeg", "image/png", "image/webp"):
            raise ValueError("mime_type must be image/jpeg, image/png, or image/webp")
        if image.startswith("data:"):
            if ";base64," not in image:
                raise ValueError("image data URI must use base64 encoding")
            data_uri = image
            encoded = image.split(",", 1)[1]
        else:
            data_uri = f"data:{mime_type};base64,{image}"
            encoded = image
        try:
            decoded = base64.b64decode(encoded, validate=True)
        except Exception as exc:
            raise ValueError("image is not valid base64") from exc
        if len(decoded) > MAX_IMAGE_BYTES:
            raise ValueError(f"image exceeds {MAX_IMAGE_BYTES} bytes")
        timestamp_ms = self._nonnegative_int(
            event.get("timestamp_ms", 0), "timestamp_ms"
        )
        signature_payload = {
            "bytes_sha256": hashlib.sha256(decoded).hexdigest(),
            "data_uri_header": data_uri.split(",", 1)[0],
            "image_role": image_role,
            "timestamp_ms": timestamp_ms,
        }
        frame_signature = hashlib.sha256(
            json.dumps(
                signature_payload,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        if seq in turn.image_seqs:
            if turn.image_frame_signatures.get(seq) != frame_signature:
                raise ValueError(
                    f"image seq {seq} conflicts with the previously accepted frame"
                )
            turn.duplicate_image_frames += 1
            await self._ack_media(
                turn, "image", seq, duplicate=True, image_role=image_role
            )
            return
        if len(turn.images) >= MAX_IMAGES_PER_TURN:
            raise ValueError(f"image frame count exceeds {MAX_IMAGES_PER_TURN}")
        frame = ImageFrame(
            seq=seq,
            timestamp_ms=timestamp_ms,
            data_uri=data_uri,
            image_role=image_role,
        )
        frame.preprocess_task = asyncio.create_task(
            self._prepare_image_frame(turn, seq=seq, decoded=decoded),
            name=f"image-preprocess-{turn.turn_id}-{seq}",
        )
        turn.images.append(frame)
        scheduled_frames = [
            item for item in turn.images if item.preprocess_task is not None
        ]
        while len(scheduled_frames) > MAX_IMAGE_PREPROCESS_TASKS_PER_TURN:
            self._discard_image_preprocess(turn, scheduled_frames.pop(0))
        turn.image_seqs.add(seq)
        turn.image_frame_signatures[seq] = frame_signature
        if turn.first_image_received_at is None:
            turn.first_image_received_at = time.perf_counter()
            emit_structured_log(
                "lifecycle",
                "turn_first_image_received",
                session_id=self.session_id,
                turn_id=turn.turn_id,
                trace_id=turn.trace_id,
                seq=seq,
                image_bytes=len(decoded),
                mime_type=mime_type,
            )
        await self._ack_media(turn, "image", seq, image_role=image_role)
    async def handle_text_update(self, event: dict[str, Any]) -> None:
        turn = self._require_collecting_turn(event)
        text = event.get("text")
        if text is not None and not isinstance(text, str):
            raise ValueError("text must be a string or null")
        turn.text = text
        if text and turn.first_text_received_at is None:
            turn.first_text_received_at = time.perf_counter()
            emit_structured_log(
                "lifecycle",
                "turn_first_text_received",
                session_id=self.session_id,
                turn_id=turn.turn_id,
                trace_id=turn.trace_id,
                chars=len(text),
            )
        await self.send(
            {
                "type": (
                    "input.text.ack"
                    if self.protocol_version is not None
                    else "turn.text.updated"
                ),
                "session_id": self.session_id,
                "turn_id": turn.turn_id,
                "text_present": bool(text),
            }
        )
    async def handle_turn_cancel(self, event: dict[str, Any]) -> None:
        turn_id = event.get("turn_id")
        if turn_id in self.cancelled_turn_ids:
            return
        if (
            self.active_turn is None or self.active_turn.turn_id != turn_id
        ) and turn_id in self.used_turn_ids:
            # Completion and cancellation may cross on the wire. Preserve the
            # first terminal state without emitting an error or second terminal.
            return
        turn = self._require_turn(event)
        emit_structured_log(
            "lifecycle",
            "turn_cancel_received",
            level="warning",
            session_id=self.session_id,
            turn_id=turn.turn_id,
            trace_id=turn.trace_id,
            phase=turn.phase,
        )
        await self._cancel_active_turn(send_event=True, expected_turn=turn)
        self.cancelled_turn_ids.add(turn.turn_id)
    async def handle_knowledge_script_event(self, event: dict[str, Any]) -> None:
        self._require_started()
        if self.active_turn is not None:
            raise ValueError(
                "knowledge.script.event cannot run while a turn is active"
            )
        if self.knowledge_binding is None:
            raise ValueError(
                "knowledge.script.event requires a bound knowledge session"
            )
        if self.knowledge_binding.mode == "provided_context":
            # The entity snapshot is immutable for the whole Session. Script
            # lifecycle remains protocol-compatible but intentionally has no
            # online Knowledge side effect in provided-context mode.
            await self.send(
                {
                    "type": "knowledge.script.event.ack",
                    "session_id": self.session_id,
                    "request_id": event["request_id"],
                    "event": event["event"],
                    "script_id": event["script_id"],
                    "status": "accepted",
                    "snapshot_id": self.knowledge_binding.snapshot_id,
                }
            )
            return
        if self.knowledge_controller is None:
            raise ValueError(
                "knowledge.script.event requires Knowledge Gateway integration"
            )
        await self._wait_for_knowledge_commit()
        async with self._knowledge_state_lock:
            self.knowledge_binding = await self.knowledge_controller.script_event(
                binding=self.knowledge_binding,
                session_id=self.session_id,
                turn_id=event["request_id"],
                script_id=event["script_id"],
                event=event["event"],
                script_version=event["script_version"],
                checksum=event["checksum"],
            )
        await self.send(
            {
                "type": "knowledge.script.event.ack",
                "session_id": self.session_id,
                "request_id": event["request_id"],
                "event": event["event"],
                "script_id": event["script_id"],
                "status": "accepted",
                "snapshot_id": self.knowledge_binding.snapshot_id,
            }
        )
    async def handle_session_close(self, event: dict[str, Any]) -> None:
        reason = event.get("reason")
        self.closed = True
        await self._cancel_active_turn(send_event=False)
        pending_commit = self._knowledge_commit_task
        if pending_commit is not None:
            try:
                await asyncio.wait_for(
                    asyncio.shield(pending_commit),
                    timeout=(
                        self.knowledge_controller.config.commit_recovery_timeout_ms
                        / 1000
                    ),
                )
            except Exception:
                logger.warning(
                    "knowledge commit did not settle before session close "
                    "session_id=%s",
                    self.session_id,
                    exc_info=True,
                )
        await self._shutdown_session_memory()
        if self.embedded_tts is not None:
            await self.embedded_tts.close()
        await self.send({"type": "session.closed", "session_id": self.session_id})
        emit_structured_log(
            "lifecycle",
            "session_closed",
            session_id=self.session_id,
            reason=reason,
            modalities=list(self.modalities),
            completed_reply_turn_count=len(self.reply_history_turns),
            completed_action_turn_count=len(self.history_turns),
            assumed_executed_action_count=len(self.executed_action_history),
            last_executed_action=self._executed_action_log_fields(
                self.last_executed_action
            ),
            last_user_executed_action=self._executed_action_log_fields(
                self.last_user_executed_action
            ),
        )
    async def _cancel_active_turn(
        self,
        *,
        send_event: bool,
        expected_turn: TurnBuffer | None = None,
    ) -> None:
        turn = self.active_turn
        if turn is None:
            return
        if expected_turn is not None and turn is not expected_turn:
            return

        cancel_started = time.perf_counter()
        if turn.phase == TURN_PHASE_PROCESSING:
            request_ids = list(turn.active_request_ids)
            turn.phase = TURN_PHASE_CANCELLING
            # Stop externally visible audio before waiting for model aborts.
            # Abort RPCs may take long enough for the provider to emit more
            # audio, which can otherwise arrive after the client cancelled.
            if self.embedded_tts is not None:
                tts_cancel_started = time.perf_counter()
                await self.embedded_tts.cancel_active_turn()
                emit_structured_log(
                    "performance",
                    "session_tts_cancel_completed",
                    session_id=self.session_id,
                    turn_id=turn.turn_id,
                    trace_id=turn.trace_id,
                    elapsed_ms=round(
                        (time.perf_counter() - tts_cancel_started) * 1000, 3
                    ),
                )
            if (
                turn.provisional_reply is not None
                and turn.provisional_reply.status == "pending"
            ):
                await self._discard_provisional_reply(
                    turn,
                    turn.provisional_reply,
                    reason="turn_cancelled",
                    send_event=send_event,
                    abort_request=False,
                )
            abort = getattr(self.client, "abort", None)
            if callable(abort):
                abort_started = time.perf_counter()
                emit_structured_log(
                    "performance",
                    "model_abort_begin",
                    session_id=self.session_id,
                    turn_id=turn.turn_id,
                    trace_id=turn.trace_id,
                    request_count=len(request_ids),
                )
                abort_results = await asyncio.gather(
                    *(abort(request_id) for request_id in request_ids),
                    return_exceptions=True,
                )
                for request_id, result in zip(request_ids, abort_results):
                    if isinstance(result, Exception):
                        logger.error(
                            "[SESSION_ACTION_REALTIME] direct abort failed "
                            "session_id=%s turn_id=%s request_id=%s error=%s",
                            self.session_id,
                            turn.turn_id,
                            request_id,
                            result,
                        )
                emit_structured_log(
                    "performance",
                    "model_abort_completed",
                    session_id=self.session_id,
                    turn_id=turn.turn_id,
                    trace_id=turn.trace_id,
                    request_count=len(request_ids),
                    failure_count=sum(
                        isinstance(result, Exception) for result in abort_results
                    ),
                    elapsed_ms=round((time.perf_counter() - abort_started) * 1000, 3),
                )
            branch_tasks = [task for task in turn.branch_tasks if not task.done()]
            for branch_task in branch_tasks:
                branch_task.cancel()
            if branch_tasks:
                await asyncio.gather(*branch_tasks, return_exceptions=True)
            task = turn.inference_task
            if (
                task is not None
                and task is not asyncio.current_task()
                and not task.done()
            ):
                task.cancel()
                await asyncio.gather(task, return_exceptions=True)
            emit_structured_log(
                "performance",
                "turn_branches_drained",
                session_id=self.session_id,
                turn_id=turn.turn_id,
                trace_id=turn.trace_id,
                branch_task_count=len(branch_tasks),
            )

        image_tasks = [
            frame.preprocess_task
            for frame in turn.images
            if frame.preprocess_task is not None
        ]
        for image_task in image_tasks:
            if not image_task.done():
                image_task.cancel()
        if image_tasks:
            await asyncio.gather(*image_tasks, return_exceptions=True)

        if (
            self.session_memory_store is not None
            and turn.turn_origin == TURN_ORIGIN_USER
        ):
            # A cancelled user turn is intentionally not extracted, but its
            # sequence must be settled so later successful turns do not leave
            # the contiguous memory watermark permanently behind.
            self._settle_session_memory_turn_without_extraction(turn)

        if self.active_turn is turn:
            self.active_turn = None
        turn.current_request_id = None
        turn.active_request_ids.clear()
        turn.branch_tasks.clear()
        turn.images.clear()
        turn.audio.clear()
        logger.info(
            "[SESSION_ACTION_REALTIME] turn cancelled session_id=%s turn_id=%s "
            "phase=%s elapsed_ms=%.3f",
            self.session_id,
            turn.turn_id,
            turn.phase,
            (time.perf_counter() - cancel_started) * 1000.0,
        )
        if send_event:
            sent = await self.send(
                {
                    "type": "turn.cancelled",
                    "session_id": self.session_id,
                    "turn_id": turn.turn_id,
                }
            )
            if sent:
                emit_structured_log(
                    "lifecycle",
                    "turn_cancelled_sent",
                    level="warning",
                    session_id=self.session_id,
                    turn_id=turn.turn_id,
                    trace_id=turn.trace_id,
                    elapsed_ms=round(
                        (time.perf_counter() - cancel_started) * 1000.0, 3
                    ),
                )
        emit_structured_log(
            "lifecycle",
            "turn_cancelled",
            level="warning",
            session_id=self.session_id,
            turn_id=turn.turn_id,
            trace_id=turn.trace_id,
            elapsed_ms=round((time.perf_counter() - cancel_started) * 1000.0, 3),
        )
    async def _ack_media(
        self,
        turn: TurnBuffer,
        media_type: str,
        seq: int,
        duplicate: bool = False,
        image_role: str | None = None,
    ) -> None:
        payload = {
            "type": "input.ack",
            "session_id": self.session_id,
            "turn_id": turn.turn_id,
            "media_type": media_type,
            "seq": seq,
            "duplicate": duplicate,
        }
        if image_role is not None:
            if self.protocol_version is not None:
                payload["image_source"] = (
                    IMAGE_SOURCE_AVATAR_CURRENT
                    if image_role == IMAGE_ROLE_AVATAR_STATE
                    else image_role
                )
            else:
                payload["image_role"] = image_role
        await self.send(payload)
    def _require_started(self) -> None:
        if not self.started or self.session_id is None:
            raise ValueError("session.start must be sent first")
    @staticmethod
    def _parse_turn_semantics(
        event: dict[str, Any],
    ) -> tuple[
        Literal["user", "proactive"],
        Literal["user_input", "character_reply"],
        str | None,
    ]:
        turn_origin = event.get("turn_origin")
        text_role = event.get("text_role")
        expected_text_role = TURN_TEXT_ROLE_BY_ORIGIN.get(turn_origin)
        if expected_text_role is None:
            raise ValueError("turn_origin must be 'user' or 'proactive'")
        if text_role != expected_text_role:
            raise ValueError(
                f"text_role must be {expected_text_role!r} when "
                f"turn_origin is {turn_origin!r}"
            )
        trigger = event.get("trigger")
        if trigger is not None:
            if not isinstance(trigger, str) or not trigger.strip():
                raise ValueError("trigger must be a non-empty string or null")
            trigger = trigger.strip()
        if turn_origin == TURN_ORIGIN_USER and trigger is not None:
            raise ValueError("trigger is only supported for proactive turns")
        return turn_origin, text_role, trigger
    def _require_turn(self, event: dict[str, Any]) -> TurnBuffer:
        self._require_started()
        if self.active_turn is None:
            raise ValueError(
                "turn already committed or no active turn exists; send turn.start first"
            )
        turn_id = event.get("turn_id")
        if turn_id != self.active_turn.turn_id:
            raise ValueError("turn_id does not match the active turn")
        return self.active_turn
    def _require_collecting_turn(self, event: dict[str, Any]) -> TurnBuffer:
        turn = self._require_turn(event)
        if turn.phase != TURN_PHASE_COLLECTING:
            raise ValueError("turn already committed")
        return turn


MultimodalTurnInputMixin = TurnInputComponent
